[debug] [2018-04-16T06:08:04.611Z] ----------------------------------------------------------------------
[debug] [2018-04-16T06:08:04.614Z] Command:       C:\Program Files\nodejs\node.exe D:\code\node_modules\firebase-tools\bin\firebase login
[debug] [2018-04-16T06:08:04.615Z] CLI Version:   3.18.4
[debug] [2018-04-16T06:08:04.615Z] Platform:      win32
[debug] [2018-04-16T06:08:04.615Z] Node Version:  v8.9.4
[debug] [2018-04-16T06:08:04.615Z] Time:          Mon Apr 16 2018 08:08:04 GMT+0200 (Mitteleuropäische Sommerzeit)
[debug] [2018-04-16T06:08:04.615Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=839988551&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2018-04-16T06:08:36.696Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AABnsl1DpJ1dISLDBv_qul9dW06E1lL6ragNYpING9J0w5OYRPT9docXCp6yuHXxaDPPU8J4dvZJuV3TZJjgLuQ',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Mon Apr 16 2018 08:08:36 GMT+0200 (Mitteleuropäische Sommerzeit)
[debug] [2018-04-16T06:08:37.710Z] Token Fetch Error: Error
    at new FirebaseError (D:\code\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (D:\code\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (D:\code\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\code\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
[debug] [2018-04-16T06:10:16.836Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  
 { code: '4/AACBf-nfasrxTDNP7KBQ7gS5HjER2Ect2TZtaO-3pbuUTl578tHQ7FFYPXx4Htmtg1YHzd_3Sn-faza9HaZARzY',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  redirect_uri: 'http://localhost:9005',
  grant_type: 'authorization_code' } 
 Mon Apr 16 2018 08:10:16 GMT+0200 (Mitteleuropäische Sommerzeit)
[debug] [2018-04-16T06:10:17.844Z] Token Fetch Error: Error
    at new FirebaseError (D:\code\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (D:\code\node_modules\firebase-tools\lib\api.js:35:11)
    at self.callback (D:\code\node_modules\firebase-tools\node_modules\request\request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\code\node_modules\firebase-tools\node_modules\request\request.js:878:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
